name: Release Version

on:
  push:
    branches:
      - main # Runs only when merging to main
    tag:
      - 'v2.*' # Runs only when pushing a new tag

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: # ✅ ADD THIS
      contents: write # Required to push commits/tags

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Ensure using Node.js 20+

      - name: Install dependencies
        run: npm install --save-dev semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/npm conventional-changelog-conventionalcommits @semantic-release/exec

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure GitHub token is used
        run: npx semantic-release

      - name: Create and push version branch
        if: success()
        run: |
           VERSION=$(node -p "require('./package.json').version")
           echo "Version from package.json is $VERSION"
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
           git checkout -b $VERSION
           git push origin $VERSION